package org.supposition.db.auto;

import java.util.List;

/** Class _Company was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Company extends org.apache.cayenne.CayenneDataObject {

    public static final String ADDITIONALS_PROPERTY = "additionals";
    public static final String CITY_PROPERTY = "city";
    public static final String GUUID_PROPERTY = "guuid";
    public static final String NAME_PROPERTY = "name";
    public static final String UPDATED_PROPERTY = "updated";
    public static final String UUID_PROPERTY = "uuid";
    public static final String UUUID_PROPERTY = "uuuid";
    public static final String WWW_PROPERTY = "www";
    public static final String ADS_PROPERTY = "ads";
    public static final String CGROUP_PROPERTY = "cgroup";
    public static final String GROUPS_PROPERTY = "groups";
    public static final String USER_PROPERTY = "user";

    public static final String ID_PK_COLUMN = "id";

    public void setAdditionals(String additionals) {
        writeProperty("additionals", additionals);
    }
    public String getAdditionals() {
        return (String)readProperty("additionals");
    }
    
    
    public void setCity(String city) {
        writeProperty("city", city);
    }
    public String getCity() {
        return (String)readProperty("city");
    }
    
    
    public void setGuuid(String guuid) {
        writeProperty("guuid", guuid);
    }
    public String getGuuid() {
        return (String)readProperty("guuid");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void setUpdated(java.util.Date updated) {
        writeProperty("updated", updated);
    }
    public java.util.Date getUpdated() {
        return (java.util.Date)readProperty("updated");
    }
    
    
    public void setUuid(String uuid) {
        writeProperty("uuid", uuid);
    }
    public String getUuid() {
        return (String)readProperty("uuid");
    }
    
    
    public void setUuuid(String uuuid) {
        writeProperty("uuuid", uuuid);
    }
    public String getUuuid() {
        return (String)readProperty("uuuid");
    }
    
    
    public void setWww(String www) {
        writeProperty("www", www);
    }
    public String getWww() {
        return (String)readProperty("www");
    }
    
    
    public void addToAds(org.supposition.db.Ads obj) {
        addToManyTarget("ads", obj, true);
    }
    public void removeFromAds(org.supposition.db.Ads obj) {
        removeToManyTarget("ads", obj, true);
    }
    public List getAds() {
        return (List)readProperty("ads");
    }
    
    
    public void setCgroup(org.supposition.db.Cgroup cgroup) {
        setToOneTarget("cgroup", cgroup, true);
    }

    public org.supposition.db.Cgroup getCgroup() {
        return (org.supposition.db.Cgroup)readProperty("cgroup");
    } 
    
    
    public void addToGroups(org.supposition.db.Group obj) {
        addToManyTarget("groups", obj, true);
    }
    public void removeFromGroups(org.supposition.db.Group obj) {
        removeToManyTarget("groups", obj, true);
    }
    public List getGroups() {
        return (List)readProperty("groups");
    }
    
    
    public void setUser(org.supposition.db.User user) {
        setToOneTarget("user", user, true);
    }

    public org.supposition.db.User getUser() {
        return (org.supposition.db.User)readProperty("user");
    } 
    
    
}
