package org.supposition.db.auto;

/** Class _Ads was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Ads extends org.apache.cayenne.CayenneDataObject {

    public static final String PRICE_PROPERTY = "price";
    public static final String TEXT_PROPERTY = "text";
    public static final String TYPE_PROPERTY = "type";
    public static final String UUID_PROPERTY = "uuid";

    public static final String ID_PK_COLUMN = "id";

    public void setPrice(String price) {
        writeProperty("price", price);
    }
    public String getPrice() {
        return (String)readProperty("price");
    }
    
    
    public void setText(String text) {
        writeProperty("text", text);
    }
    public String getText() {
        return (String)readProperty("text");
    }
    
    
    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }
    
    
    public void setUuid(String uuid) {
        writeProperty("uuid", uuid);
    }
    public String getUuid() {
        return (String)readProperty("uuid");
    }
    
    
}
