package org.supposition.db.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _RootMenu was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RootMenu extends CayenneDataObject {

    public static final String ROOT_ID_PROPERTY = "RootID";
    public static final String VALIDATOR_PROPERTY = "validator";

    public static final String ID_PK_COLUMN = "ID";

    public void setRootID(String RootID) {
        writeProperty("RootID", RootID);
    }
    public String getRootID() {
        return (String)readProperty("RootID");
    }

    public void setValidator(String validator) {
        writeProperty("validator", validator);
    }
    public String getValidator() {
        return (String)readProperty("validator");
    }

}
